-- Migracja: Wstawienie danych do dictionary_region_events
-- ============================================

INSERT INTO public.dictionary_region_events (phase_code, region_code, label, description, utc_start, utc_end, wraps_midnight, priority, volatility_level, volume_impact, typical_duration_min, trading_pattern, dominant_actors, news_sensitivity, category) VALUES
    ('CN_MORNING_PEAK', 'CN', 'China Morning Peak', 'Poranne okno aktywności w Chinach (lokalny 7:00-10:00)', '23:00', '02:00', TRUE, 10, 'MEDIUM', 'HIGH', 180, 'TRENDING', 'RETAIL', 'MEDIUM', 'SESSION'),
    ('CN_LUNCH_BREAK', 'CN', 'China Lunch Break', 'Przerwa obiadowa - spadek aktywności (lokalny 12:00-14:00)', '04:00', '06:00', FALSE, 18, 'LOW', 'LOW', 120, 'RANGING', 'RETAIL', 'LOW', 'LIQUIDITY'),
    ('CN_EVENING_PEAK', 'CN', 'China Evening Peak', 'Wieczorne okno aktywności w Chinach (lokalny 19:00-23:00)', '11:00', '15:00', FALSE, 10, 'MEDIUM', 'HIGH', 240, 'MIXED', 'RETAIL', 'MEDIUM', 'SESSION'),
    ('RU_MORNING_PEAK', 'RU', 'Russia Morning Peak', 'Poranna aktywność w Rosji (MSK 7:00-10:00)', '04:00', '07:00', FALSE, 10, 'MEDIUM', 'MEDIUM', 180, 'MIXED', 'RETAIL', 'MEDIUM', 'SESSION'),
    ('RU_EVENING_PEAK', 'RU', 'Russia Evening Peak', 'Wieczorne okno aktywności w Rosji (MSK 18:00-22:00)', '15:00', '19:00', FALSE, 10, 'MEDIUM', 'MEDIUM', 240, 'MIXED', 'RETAIL', 'MEDIUM', 'SESSION'),
    ('SG_MORNING_PEAK', 'SG', 'Singapore Morning Peak', 'Poranne okno aktywności w Singapurze', '22:00', '01:00', TRUE, 10, 'MEDIUM', 'HIGH', 180, 'TRENDING', 'INSTITUTIONAL', 'MEDIUM', 'SESSION'),
    ('SG_TRADING_HOURS', 'SG', 'Singapore Trading Hours', 'Główne godziny handlu w Singapurze', '00:00', '08:00', FALSE, 12, 'MEDIUM', 'HIGH', 480, 'MIXED', 'INSTITUTIONAL', 'MEDIUM', 'SESSION'),
    ('SG_EVENING_PEAK', 'SG', 'Singapore Evening Peak', 'Wieczorne okno aktywności w Singapurze', '10:00', '14:00', FALSE, 10, 'MEDIUM', 'MEDIUM', 240, 'MIXED', 'MIXED', 'MEDIUM', 'SESSION'),
    ('US_PREMARKET', 'US', 'US Pre-Market', 'Aktywność przed otwarciem giełd USA', '12:00', '13:30', FALSE, 9, 'MEDIUM', 'MEDIUM', 90, 'RANGING', 'INSTITUTIONAL', 'MEDIUM', 'SESSION'),
    ('US_MORNING_PEAK', 'US', 'US Morning Peak', 'Poranna aktywność inwestorów w USA (NYSE open)', '13:30', '15:00', FALSE, 7, 'HIGH', 'HIGH', 90, 'VOLATILE', 'INSTITUTIONAL', 'HIGH', 'SESSION'),
    ('US_AFTERNOON_PEAK', 'US', 'US Afternoon Peak', 'Popołudniowy szczyt aktywności w USA', '15:00', '17:00', FALSE, 8, 'HIGH', 'HIGH', 120, 'TRENDING', 'INSTITUTIONAL', 'MEDIUM', 'SESSION'),
    ('US_POWER_HOUR', 'US', 'US Power Hour', 'Ostatnia godzina sesji NYSE - intensywny handel', '19:00', '20:00', FALSE, 6, 'HIGH', 'HIGH', 60, 'VOLATILE', 'INSTITUTIONAL', 'MEDIUM', 'SESSION'),
    ('US_EVENING_PEAK', 'US', 'US Evening Peak', 'Wieczorne okno aktywności w USA', '20:00', '23:00', FALSE, 12, 'MEDIUM', 'MEDIUM', 180, 'RANGING', 'RETAIL', 'LOW', 'SESSION'),
    ('KR_MORNING_PEAK', 'KR', 'Korea Morning Peak', 'Poranna aktywność w Korei Południowej', '23:00', '02:00', TRUE, 10, 'MEDIUM', 'HIGH', 180, 'TRENDING', 'RETAIL', 'MEDIUM', 'SESSION'),
    ('KR_KIMCHI_PREMIUM', 'KR', 'Korea Kimchi Premium Window', 'Okno potencjalnej premii Kimchi (różnica cen KR vs. globalne)', '00:00', '04:00', FALSE, 8, 'MEDIUM', 'HIGH', 240, 'MIXED', 'RETAIL', 'MEDIUM', 'SESSION'),
    ('KR_EVENING_PEAK', 'KR', 'Korea Evening Peak', 'Wieczorne okno aktywności w Korei', '10:00', '14:00', FALSE, 10, 'MEDIUM', 'MEDIUM', 240, 'MIXED', 'RETAIL', 'MEDIUM', 'SESSION'),
    ('JP_MORNING_PEAK', 'JP', 'Japan Morning Peak', 'Poranna aktywność w Japonii (TSE open)', '00:00', '03:00', FALSE, 10, 'MEDIUM', 'HIGH', 180, 'TRENDING', 'INSTITUTIONAL', 'MEDIUM', 'SESSION'),
    ('JP_EVENING_PEAK', 'JP', 'Japan Evening Peak', 'Wieczorne okno aktywności w Japonii', '10:00', '14:00', FALSE, 10, 'MEDIUM', 'MEDIUM', 240, 'MIXED', 'MIXED', 'MEDIUM', 'SESSION'),
    ('GB_MORNING_PEAK', 'GB', 'UK Morning Peak', 'Poranna aktywność w Wielkiej Brytanii (LSE open)', '07:00', '10:00', FALSE, 9, 'MEDIUM', 'HIGH', 180, 'TRENDING', 'INSTITUTIONAL', 'HIGH', 'SESSION'),
    ('GB_AFTERNOON_PEAK', 'GB', 'UK Afternoon Peak', 'Popołudniowa aktywność w UK', '14:00', '16:30', FALSE, 10, 'HIGH', 'HIGH', 150, 'VOLATILE', 'INSTITUTIONAL', 'HIGH', 'SESSION'),
    ('GB_EVENING_PEAK', 'GB', 'UK Evening Peak', 'Wieczorne okno aktywności w UK', '18:00', '21:00', FALSE, 12, 'MEDIUM', 'MEDIUM', 180, 'RANGING', 'RETAIL', 'LOW', 'SESSION'),
    ('DE_MORNING_PEAK', 'DE', 'Germany Morning Peak', 'Poranna aktywność w Niemczech (Xetra open)', '07:00', '10:00', FALSE, 10, 'MEDIUM', 'HIGH', 180, 'TRENDING', 'INSTITUTIONAL', 'HIGH', 'SESSION'),
    ('DE_AFTERNOON_PEAK', 'DE', 'Germany Afternoon Peak', 'Popołudniowa aktywność w Niemczech', '13:00', '16:00', FALSE, 10, 'HIGH', 'HIGH', 180, 'VOLATILE', 'INSTITUTIONAL', 'HIGH', 'SESSION'),
    ('DE_EVENING_PEAK', 'DE', 'Germany Evening Peak', 'Wieczorne okno aktywności w Niemczech', '17:00', '20:00', FALSE, 12, 'MEDIUM', 'MEDIUM', 180, 'RANGING', 'RETAIL', 'LOW', 'SESSION'),
    ('PL_MORNING_PEAK', 'PL', 'Poland Morning Peak', 'Poranne okno aktywności inwestorów w Polsce', '06:00', '09:00', FALSE, 10, 'MEDIUM', 'MEDIUM', 180, 'MIXED', 'RETAIL', 'MEDIUM', 'SESSION'),
    ('PL_AFTERNOON_PEAK', 'PL', 'Poland Afternoon Peak', 'Popołudniowa aktywność w Polsce', '13:00', '16:00', FALSE, 12, 'MEDIUM', 'MEDIUM', 180, 'MIXED', 'RETAIL', 'MEDIUM', 'SESSION'),
    ('PL_EVENING_PEAK', 'PL', 'Poland Evening Peak', 'Wieczorne okno aktywności inwestorów w Polsce', '17:00', '21:00', FALSE, 10, 'MEDIUM', 'MEDIUM', 240, 'MIXED', 'RETAIL', 'LOW', 'SESSION'),
    ('HK_MORNING_PEAK', 'HK', 'Hong Kong Morning Peak', 'Poranna aktywność w Hong Kongu (HKEX open)', '01:00', '04:00', FALSE, 9, 'MEDIUM', 'HIGH', 180, 'TRENDING', 'INSTITUTIONAL', 'MEDIUM', 'SESSION'),
    ('HK_AFTERNOON_PEAK', 'HK', 'Hong Kong Afternoon Peak', 'Popołudniowa aktywność w Hong Kongu', '05:00', '08:00', FALSE, 10, 'MEDIUM', 'HIGH', 180, 'MIXED', 'INSTITUTIONAL', 'MEDIUM', 'SESSION'),
    ('HK_EVENING_PEAK', 'HK', 'Hong Kong Evening Peak', 'Wieczorne okno aktywności w Hong Kongu', '10:00', '14:00', FALSE, 12, 'MEDIUM', 'MEDIUM', 240, 'MIXED', 'MIXED', 'MEDIUM', 'SESSION'),
    ('AE_MORNING_PEAK', 'AE', 'UAE Morning Peak', 'Poranna aktywność w Dubaju (DFM open)', '04:00', '07:00', FALSE, 10, 'MEDIUM', 'MEDIUM', 180, 'MIXED', 'INSTITUTIONAL', 'MEDIUM', 'SESSION'),
    ('AE_BRIDGE_SESSION', 'AE', 'UAE Bridge Session', 'Dubaj jako most między Azją a Europą', '05:00', '08:00', FALSE, 8, 'MEDIUM', 'MEDIUM', 180, 'TRENDING', 'INSTITUTIONAL', 'MEDIUM', 'OVERLAP'),
    ('AE_EVENING_PEAK', 'AE', 'UAE Evening Peak', 'Wieczorne okno aktywności w Dubaju', '14:00', '18:00', FALSE, 12, 'MEDIUM', 'MEDIUM', 240, 'MIXED', 'MIXED', 'LOW', 'SESSION'),
    ('AU_MORNING_PEAK', 'AU', 'Australia Morning Peak', 'Poranna aktywność w Australii (ASX open)', '22:00', '01:00', TRUE, 10, 'MEDIUM', 'MEDIUM', 180, 'MIXED', 'INSTITUTIONAL', 'MEDIUM', 'SESSION'),
    ('AU_AFTERNOON_PEAK', 'AU', 'Australia Afternoon Peak', 'Popołudniowa aktywność w Australii', '03:00', '06:00', FALSE, 12, 'LOW', 'LOW', 180, 'RANGING', 'RETAIL', 'LOW', 'SESSION'),
    ('AU_EVENING_PEAK', 'AU', 'Australia Evening Peak', 'Wieczorne okno aktywności w Australii', '08:00', '12:00', FALSE, 12, 'MEDIUM', 'MEDIUM', 240, 'MIXED', 'RETAIL', 'MEDIUM', 'SESSION'),
    ('BR_MORNING_PEAK', 'BR', 'Brazil Morning Peak', 'Poranna aktywność w Brazylii (B3 open)', '12:00', '15:00', FALSE, 10, 'MEDIUM', 'MEDIUM', 180, 'MIXED', 'MIXED', 'MEDIUM', 'SESSION'),
    ('BR_AFTERNOON_PEAK', 'BR', 'Brazil Afternoon Peak', 'Popołudniowa aktywność w Brazylii', '17:00', '20:00', FALSE, 12, 'MEDIUM', 'MEDIUM', 180, 'MIXED', 'RETAIL', 'MEDIUM', 'SESSION'),
    ('BR_EVENING_PEAK', 'BR', 'Brazil Evening Peak', 'Wieczorne okno aktywności w Brazylii', '21:00', '00:00', TRUE, 14, 'MEDIUM', 'LOW', 180, 'RANGING', 'RETAIL', 'LOW', 'SESSION'),
    ('IN_MORNING_PEAK', 'IN', 'India Morning Peak', 'Poranna aktywność w Indiach (NSE open)', '03:30', '06:30', FALSE, 10, 'MEDIUM', 'MEDIUM', 180, 'MIXED', 'RETAIL', 'MEDIUM', 'SESSION'),
    ('IN_AFTERNOON_PEAK', 'IN', 'India Afternoon Peak', 'Popołudniowa aktywność w Indiach', '09:00', '12:00', FALSE, 12, 'MEDIUM', 'MEDIUM', 180, 'MIXED', 'RETAIL', 'MEDIUM', 'SESSION'),
    ('IN_EVENING_PEAK', 'IN', 'India Evening Peak', 'Wieczorne okno aktywności w Indiach', '14:00', '18:00', FALSE, 12, 'MEDIUM', 'MEDIUM', 240, 'MIXED', 'RETAIL', 'MEDIUM', 'SESSION'),
    ('TR_MORNING_PEAK', 'TR', 'Turkey Morning Peak', 'Poranna aktywność w Turcji (Borsa Istanbul open)', '06:00', '09:00', FALSE, 10, 'MEDIUM', 'MEDIUM', 180, 'MIXED', 'RETAIL', 'MEDIUM', 'SESSION'),
    ('TR_AFTERNOON_PEAK', 'TR', 'Turkey Afternoon Peak', 'Popołudniowa aktywność w Turcji', '12:00', '15:00', FALSE, 12, 'MEDIUM', 'MEDIUM', 180, 'MIXED', 'RETAIL', 'MEDIUM', 'SESSION'),
    ('TR_EVENING_PEAK', 'TR', 'Turkey Evening Peak', 'Wieczorne okno aktywności w Turcji (wysoka adopcja crypto)', '16:00', '20:00', FALSE, 10, 'MEDIUM', 'MEDIUM', 240, 'MIXED', 'RETAIL', 'LOW', 'SESSION'),
    ('CA_MORNING_PEAK', 'CA', 'Canada Morning Peak', 'Poranna aktywność w Kanadzie (TSX open)', '13:30', '16:00', FALSE, 10, 'MEDIUM', 'MEDIUM', 150, 'MIXED', 'INSTITUTIONAL', 'HIGH', 'SESSION'),
    ('CA_AFTERNOON_PEAK', 'CA', 'Canada Afternoon Peak', 'Popołudniowa aktywność w Kanadzie', '17:00', '20:00', FALSE, 12, 'MEDIUM', 'MEDIUM', 180, 'MIXED', 'RETAIL', 'MEDIUM', 'SESSION')
ON CONFLICT (phase_code) DO NOTHING;

